### ISSUE TITLE
Ask

### ISSUE THREAD

**Issue by AnonymousWebHacker** [Hulxv/vcs#1]
How work?
What things were implemented in this version?
How is the communication with other servers?

Could you explain more in the readme? I'm excited to try and I don't know rust hahaha.

**Comment by Hulxv** [comment]
Currently, It's not ready to use.
But that an API to get all important data which you will need to work with vnStat Client

And Well be there many endpoints like
```bash
/traffic/<interval> # (GET), for traffic data
```
```bash
/info # (GET), for Infos about vnStat and vcs
```
```bash
/interfaces # (GET), for vnStat interfaces
```
/daemon # (POST, GET), To control in vnstatd and get status

And another endpoint for authentication (For security and make data secure, Based on your suggestion) and maybe more

And you can use it by running vcs on your machine and sending HTTP requests
That's very easy and you can use it in anything like building your custom client :D.

But all that is not ready yet, So I'll try to finish it as soon as possible 

Thanks for your interest, And I will write a documentation when I finish it.


I'm very sorry for the late response, I just read your issue, I don't know why github doesn't send email when an issue opening in my repos.
